### ISSUE TITLE
crash when normally opening the program

### ISSUE THREAD

**Issue by daredevil28** [MightyPork/rpw#21]
## RPW 3.9.0 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.

Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com

### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.8.0_25
 OS name           | Windows 8.1
 File encoding     | Cp1252
 Launch dir        | C:\Users\seankelly\Desktop
 RPW version       | 3.9.0
 Library version   | 1.7.10+1.7.10
 RPW path          | C:\Users\seankelly\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\seankelly\AppData\Roaming\.minecraft

### STACK TRACE ###

```
java.lang.NullPointerException
	at net.mightypork.rpw.gui.windows.dialogs.DialogProjectProperties.<init>(DialogProjectProperties.java:57)
	at net.mightypork.rpw.tasks.Tasks.taskDialogProjectProperties(Tasks.java:750)
	at net.mightypork.rpw.gui.widgets.MenuMain$17.actionPerformed(MenuMain.java:550)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$400(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

### FULL LOG ###

```
[ i ] Main logger initialized.
[ i ] 2015/01/01 02:26:49
[ i ] ResourcePack Workbench v.3.9.0 (#390)
[ # ] Init started...
[ - ] Checking Minecraft installation.
[ - ] Checking working directory.
[ - ] Initializing configuration manager.
[   ] Last run version: 3.9.0 (#390)
[ i ] Using library version: 1.7.10+1.7.10
[ - ] Loading GUI icons
[ - ] Loading GUI icons - done.
[   ] Initializing RSyntaxTextArea
[ - ] Loading help pages
[ # ] Initializing Sources
[ - ] Loading vanilla structure
[ - ] Loading help pages - done.
[ - ] Loading vanilla structure - done.
[ - ] Erasing library cache
[ - ] Loading resourcepacks...
[   ] Adding Source: StarQuest -> C:\Users\seankelly\AppData\Roaming\.mcRPW\library\resourcepacks\StarQuest
[ # ] Initializing Sources - done.
[ - ] Building main window.
[ - ] Downloading update info
[ - ] Opening last project (if any).
[ # ] Loading project StarQuest
[ - ] Project 'StarQuest': Copying BASE->TMP
[ - ] Downloading update info - done.
[ i ] Your version is up-to-date.
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.NullPointerException
[!E!] 	at net.mightypork.rpw.gui.windows.dialogs.DialogProjectProperties.<init>(DialogProjectProperties.java:57)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskDialogProjectProperties(Tasks.java:750)
[!E!] 	at net.mightypork.rpw.gui.widgets.MenuMain$17.actionPerformed(MenuMain.java:550)
[!E!] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[!E!] 	at javax.swing.AbstractButton.doClick(Unknown Source)
[!E!] 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
[!E!] 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
[!E!] 	at java.awt.Component.processMouseEvent(Unknown Source)
[!E!] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.Component.processEvent(Unknown Source)
[!E!] 	at java.awt.Container.processEvent(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.EventQueue.access$400(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.run(Unknown Source)
[!E!] 

```

~~~ END OF REPORT ~~~

**Comment by MightyPork** [comment]
I don't see how this could happen.

Can you reproduce it? What are the steps to get this crash?

**Comment by MightyPork** [comment]
I cannot fix this without additional info.
