### ISSUE TITLE
java.lang.InternalError: Could not initialize shell library

### ISSUE THREAD

**Issue by Puddleduckable** [MightyPork/rpw#32]
Im having a bug here whenever I use the tool create project.
Here's the report.

All I can say about this I think is connected is
1.I use windows 7
2. The loader installs it, and freezes when done. Then I use Task Manager to force shut it down.
3.I use direct download, is that bad? 

Oh, also, I guess ill manually make my texture. THis is gunna be hard.

## RPW 3.9.2 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.

Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com

### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.8.0_45
 OS name           | Windows 7
 File encoding     | Cp1252
 Launch dir        | C:\Users\We Are Five\Desktop
 RPW version       | 3.9.2
 Library version   | 1.8.4+1.8
 RPW path          | C:\Users\We Are Five\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\We Are Five\AppData\Roaming\.minecraft

### STACK TRACE ###

```
java.lang.InternalError: Could not initialize shell library
	at sun.awt.shell.Win32ShellFolder2.initIDs(Native Method)
	at sun.awt.shell.Win32ShellFolder2.<clinit>(Unknown Source)
	at sun.awt.shell.Win32ShellFolderManager2.getDesktop(Unknown Source)
	at sun.awt.shell.Win32ShellFolderManager2.get(Unknown Source)
	at sun.awt.shell.ShellFolder.get(Unknown Source)
	at javax.swing.filechooser.FileSystemView.getRoots(Unknown Source)
	at javax.swing.filechooser.WindowsFileSystemView.getHomeDirectory(Unknown Source)
	at sun.swing.plaf.synth.SynthFileChooserUIImpl.installComponents(Unknown Source)
	at javax.swing.plaf.basic.BasicFileChooserUI.installUI(Unknown Source)
	at sun.swing.plaf.synth.SynthFileChooserUI.installUI(Unknown Source)
	at javax.swing.JComponent.setUI(Unknown Source)
	at javax.swing.JFileChooser.updateUI(Unknown Source)
	at javax.swing.JFileChooser.setup(Unknown Source)
	at javax.swing.JFileChooser.<init>(Unknown Source)
	at javax.swing.JFileChooser.<init>(Unknown Source)
	at net.mightypork.rpw.gui.helpers.FileChooser.<init>(FileChooser.java:65)
	at net.mightypork.rpw.gui.widgets.FileInput.<init>(FileInput.java:99)
	at net.mightypork.rpw.gui.windows.dialogs.DialogNewProject.buildGui(DialogNewProject.java:105)
	at net.mightypork.rpw.gui.windows.RpwDialog.createDialog(RpwDialog.java:130)
	at net.mightypork.rpw.gui.windows.dialogs.DialogNewProject.<init>(DialogNewProject.java:62)
	at net.mightypork.rpw.tasks.Tasks.taskDialogNewProject(Tasks.java:773)
	at net.mightypork.rpw.tasks.Tasks.taskNewProject(Tasks.java:663)
	at net.mightypork.rpw.gui.widgets.MenuMain$2.actionPerformed(MenuMain.java:416)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

### FULL LOG ###

```
[ i ] Main logger initialized.
[ i ] 2015/04/17 15:25:20
[ i ] ResourcePack Workbench v.3.9.2 (#392)
[ # ] Init started...
[ - ] Checking Minecraft installation.
[ - ] Checking working directory.
[ - ] Initializing configuration manager.
[   ] Last run version: 3.9.2 (#392)
[ i ] Using library version: 1.8.4+1.8
[ - ] Loading GUI icons
[ - ] Loading GUI icons - done.
[   ] Initializing RSyntaxTextArea
[ - ] Loading help pages
[ # ] Initializing Sources
[ - ] Loading vanilla structure
[ - ] Loading help pages - done.
[ - ] Loading vanilla structure - done.
[ - ] Erasing library cache
[ - ] Loading resourcepacks...
[ # ] Initializing Sources - done.
[ - ] Building main window.
[ - ] Downloading update info
[ - ] Opening last project (if any).
[ - ] Downloading update info - done.
[ i ] Your version is up-to-date.
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.InternalError: Could not initialize shell library
[!E!] 	at sun.awt.shell.Win32ShellFolder2.initIDs(Native Method)
[!E!] 	at sun.awt.shell.Win32ShellFolder2.<clinit>(Unknown Source)
[!E!] 	at sun.awt.shell.Win32ShellFolderManager2.getDesktop(Unknown Source)
[!E!] 	at sun.awt.shell.Win32ShellFolderManager2.get(Unknown Source)
[!E!] 	at sun.awt.shell.ShellFolder.get(Unknown Source)
[!E!] 	at javax.swing.filechooser.FileSystemView.getRoots(Unknown Source)
[!E!] 	at javax.swing.filechooser.WindowsFileSystemView.getHomeDirectory(Unknown Source)
[!E!] 	at sun.swing.plaf.synth.SynthFileChooserUIImpl.installComponents(Unknown Source)
[!E!] 	at javax.swing.plaf.basic.BasicFileChooserUI.installUI(Unknown Source)
[!E!] 	at sun.swing.plaf.synth.SynthFileChooserUI.installUI(Unknown Source)
[!E!] 	at javax.swing.JComponent.setUI(Unknown Source)
[!E!] 	at javax.swing.JFileChooser.updateUI(Unknown Source)
[!E!] 	at javax.swing.JFileChooser.setup(Unknown Source)
[!E!] 	at javax.swing.JFileChooser.<init>(Unknown Source)
[!E!] 	at javax.swing.JFileChooser.<init>(Unknown Source)
[!E!] 	at net.mightypork.rpw.gui.helpers.FileChooser.<init>(FileChooser.java:65)
[!E!] 	at net.mightypork.rpw.gui.widgets.FileInput.<init>(FileInput.java:99)
[!E!] 	at net.mightypork.rpw.gui.windows.dialogs.DialogNewProject.buildGui(DialogNewProject.java:105)
[!E!] 	at net.mightypork.rpw.gui.windows.RpwDialog.createDialog(RpwDialog.java:130)
[!E!] 	at net.mightypork.rpw.gui.windows.dialogs.DialogNewProject.<init>(DialogNewProject.java:62)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskDialogNewProject(Tasks.java:773)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskNewProject(Tasks.java:663)
[!E!] 	at net.mightypork.rpw.gui.widgets.MenuMain$2.actionPerformed(MenuMain.java:416)
[!E!] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[!E!] 	at javax.swing.AbstractButton.doClick(Unknown Source)
[!E!] 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
[!E!] 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
[!E!] 	at java.awt.Component.processMouseEvent(Unknown Source)
[!E!] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.Component.processEvent(Unknown Source)
[!E!] 	at java.awt.Container.processEvent(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.EventQueue.access$500(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.run(Unknown Source)
[!E!] 

```

~~~ END OF REPORT ~~~

**Comment by MightyPork** [comment]
I'm sorry, this is a windows-java compatibility problem, not something I can fix (or debug, since I'm on Linux).
Some things to try

- make sure your java is up to date (actually I haven't tested RPW on Java 8, but it should work)
- restart the computer
- try it again
- close other programs when running it
- sacrifice a black sheep in the full moon

I looked on google and found nothing useful, if you find anything that could help (eg. tip how to fix this), I'll try to implement it.

**Comment by MightyPork** [comment]
closing for lack of feedback
