### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by WeatherToast272** [MightyPork/rpw#45]
Whenever I try to use the RPW it just shows up with a crash report saying:

## RPW 4.1.0 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.

Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com

### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.8.0_45
 OS name           | Windows 8.1
 File encoding     | Cp1252
 Launch dir        | C:\Users\Lareen\Desktop
 RPW version       | 4.1.0
 Library version   | 1.8.3+1.8
 RPW path          | C:\Users\Lareen\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\Lareen\AppData\Roaming\.minecraft

### STACK TRACE ###

```
java.lang.NullPointerException
	at net.mightypork.rpw.project.Project.saveConfigFiles(Project.java:231)
	at net.mightypork.rpw.tasks.Tasks.taskStoreProjectChanges(Tasks.java:248)
	at net.mightypork.rpw.tasks.Tasks.taskStoreProjectChanges(Tasks.java:232)
	at net.mightypork.rpw.tasks.Tasks.taskAskToSaveIfChanged(Tasks.java:364)
	at net.mightypork.rpw.tasks.Tasks.taskExit(Tasks.java:697)
	at net.mightypork.rpw.gui.windows.WindowMain$1.onClose(WindowMain.java:57)
	at net.mightypork.rpw.gui.helpers.WindowCloseListener.windowClosing(WindowCloseListener.java:37)
	at java.awt.Window.processWindowEvent(Unknown Source)
	at javax.swing.JFrame.processWindowEvent(Unknown Source)
	at java.awt.Window.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

### FULL LOG ###

```
[ i ] Main logger initialized.
[ i ] 2015/06/14 22:20:56
[ i ] ResourcePack Workbench v.4.1.0 (#410)
[ # ] Init started...
[ - ] Checking Minecraft installation.
[ - ] Checking working directory.
[ - ] Initializing configuration manager.
[   ] Last run version: 4.1.0 (#410)
[ i ] Using library version: 1.8.3+1.8
[ - ] Loading GUI icons
[ - ] Loading GUI icons - done.
[   ] Initializing RSyntaxTextArea
[ # ] Initializing Sources
[ - ] Loading help pages
[ - ] Loading vanilla structure
[ - ] Loading help pages - done.
[ - ] Loading vanilla structure - done.
[ - ] Erasing library cache
[ - ] Loading resourcepacks...
[ # ] Initializing Sources - done.
[ - ] Building main window.
[ - ] Downloading update info
[ - ] Opening last project (if any).
[ # ] Loading project ToastCraft
[ - ] Project 'ToastCraft': Creating backup copy...
[ - ] Project 'ToastCraft': Copying - done.
[ - ] Project 'ToastCraft':  Loading from TMP
[   ] Adding RPW_README.txt to the pack
[!W!] Project 'ToastCraft': Project data files could not be loaded.
[!E!] An arror occured while loading the project.
[!E!] Please, check the log for details.
[ - ] Downloading update info - done.
[ i ] Your version is up-to-date.
[ - ] Trying to exec:
[ - ]    cmd = explorer
[ - ]    args = %s
[ - ]    %s = https://github.com/MightyPork/rpw/issues/new
[   ] Process is running.
[   ] Dialog closed: Runtime log
[   ] Dialog open: Runtime log
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.NullPointerException
[!E!] 	at net.mightypork.rpw.project.Project.saveConfigFiles(Project.java:231)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskStoreProjectChanges(Tasks.java:248)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskStoreProjectChanges(Tasks.java:232)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskAskToSaveIfChanged(Tasks.java:364)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskExit(Tasks.java:697)
[!E!] 	at net.mightypork.rpw.gui.windows.WindowMain$1.onClose(WindowMain.java:57)
[!E!] 	at net.mightypork.rpw.gui.helpers.WindowCloseListener.windowClosing(WindowCloseListener.java:37)
[!E!] 	at java.awt.Window.processWindowEvent(Unknown Source)
[!E!] 	at javax.swing.JFrame.processWindowEvent(Unknown Source)
[!E!] 	at java.awt.Window.processEvent(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.EventQueue.access$500(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.run(Unknown Source)
[!E!] 

```

~~~ END OF REPORT ~~~

If you wish to, could you please tell me how to fix this. Thank you.

**Comment by Jiggy-12321** [comment]
Looks like RPW tried to call a file that was not there.

**Comment by MightyPork** [comment]
Not really, let me check the source. Haven't seen this one yet.

**Comment by MightyPork** [comment]
Honestly, I do not understand how this could have happened. It should not be possible.

**Comment by MightyPork** [comment]
Ok we'll now just catch and log the NPE, let's hope it'll suffice.

**Comment by Jiggy-12321** [comment]
I think I figured it out
