### ISSUE TITLE
ArrayIndexOutOfBoundsException somewhere in tree painting (?)

### ISSUE THREAD

**Issue by MightyPork** [MightyPork/rpw#51]
Not sure if worth fixing, but here it is. Really rare crash.

```
[ i ] Main logger initialized.
[ i ] 2015/06/10 21:22:51
[ i ] ResourcePack Workbench v.4.1.0 (#410)
[ # ] Init started...
[ - ] Checking Minecraft installation.
[ - ] Checking working directory.
[ - ] Initializing configuration manager.
[   ] Last run version: 4.1.0 (#410)
[ i ] Using library version: 1.8.6+1.8
[ - ] Loading GUI icons
[ - ] Loading GUI icons - done.
[   ] Initializing RSyntaxTextArea
[ - ] Loading help pages
[ # ] Initializing Sources
[ - ] Loading vanilla structure
[ - ] Loading help pages - done.
[ - ] Loading vanilla structure - done.
[ - ] Erasing library cache
[ - ] Loading resourcepacks...
[   ] Adding Source: faithful32pack -> /home/ondra/.mcRPW/library/resourcepacks/faithful32pack
[ # ] Initializing Sources - done.
[ - ] Building main window.
[ - ] Downloading update info
[ - ] Opening last project (if any).
[ # ] Loading project Discordant
[ - ] Project 'Discordant': Creating backup copy...
[ - ] Project 'Discordant': Copying - done.
[ - ] Project 'Discordant':  Loading from TMP
[   ] Adding RPW_README.txt to the pack
[ - ] Downloading update info - done.
[ i ] Your version is up-to-date.
[ - ] Checking project for unsaved changes.
[   ] Project 'Discordant': Finding differences BACKUP:WORKDIR
[   ] Checksum mismatch:
[   ] Child counts differ:
[   ] /home/ondra/.mcRPW/tmp/backup-Discordant/STUFF
[   ] /home/ondra/.mcRPW/projects/Discordant/STUFF
[   ] Project 'Discordant': Changes detected
[   ] Asking to save.
[   ] - Config option AUTO_SAVE enabled, saving.
[ - ] Project 'Discordant': Creating backup copy...
[ - ] Project 'Discordant': Copying - done.
[ # ] Loading project Discordant
[ - ] Project 'Discordant': Creating backup copy...
[ - ] Project 'Discordant': Copying - done.
[ - ] Project 'Discordant':  Loading from TMP
[   ] Adding RPW_README.txt to the pack
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.ArrayIndexOutOfBoundsException: No such child: 1
[!E!] 	at java.awt.Container.getComponent(Container.java:327)
[!E!] 	at javax.swing.JComponent.rectangleIsObscured(JComponent.java:4394)
[!E!] 	at javax.swing.JComponent.paint(JComponent.java:1044)
[!E!] 	at org.jdesktop.swingx.JXPanel.paint(JXPanel.java:580)
[!E!] 	at javax.swing.CellRendererPane.paintComponent(CellRendererPane.java:151)
[!E!] 	at javax.swing.plaf.basic.BasicTreeUI.paintRow(BasicTreeUI.java:1539)
[!E!] 	at javax.swing.plaf.basic.BasicTreeUI.paint(BasicTreeUI.java:1223)
[!E!] 	at javax.swing.plaf.metal.MetalTreeUI.paint(MetalTreeUI.java:169)
[!E!] 	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
[!E!] 	at javax.swing.JComponent.paintComponent(JComponent.java:770)
[!E!] 	at javax.swing.JComponent.paint(JComponent.java:1046)
[!E!] 	at org.jdesktop.swingx.JXTreeTable$TreeTableCellRenderer.paint(JXTreeTable.java:3053)
[!E!] 	at javax.swing.CellRendererPane.paintComponent(CellRendererPane.java:151)
[!E!] 	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2109)
[!E!] 	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2010)
[!E!] 	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1806)
[!E!] 	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
[!E!] 	at javax.swing.JComponent.paintComponent(JComponent.java:770)
[!E!] 	at javax.swing.JComponent.paint(JComponent.java:1046)
[!E!] 	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5223)
[!E!] 	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:295)
[!E!] 	at javax.swing.RepaintManager.paint(RepaintManager.java:1249)
[!E!] 	at javax.swing.JComponent._paintImmediately(JComponent.java:5171)
[!E!] 	at javax.swing.JComponent.paintImmediately(JComponent.java:4982)
[!E!] 	at javax.swing.RepaintManager$3.run(RepaintManager.java:808)
[!E!] 	at javax.swing.RepaintManager$3.run(RepaintManager.java:796)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
[!E!] 	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:796)
[!E!] 	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:769)
[!E!] 	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:718)
[!E!] 	at javax.swing.RepaintManager.access$1100(RepaintManager.java:62)
[!E!] 	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1677)
[!E!] 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
[!E!] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
[!E!] 	at java.awt.EventQueue.access$300(EventQueue.java:103)
[!E!] 	at java.awt.EventQueue$3.run(EventQueue.java:706)
[!E!] 	at java.awt.EventQueue$3.run(EventQueue.java:704)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
[!E!] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
[!E!] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
[!E!] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
[!E!] 
```

**Comment by MightyPork** [comment]
No way to find how it happened

**Comment by Jiggy-12321** [comment]
lolololllolol
