### ISSUE TITLE
Fail to export. Added Custom Sound

### ISSUE THREAD

**Issue by robosheep95** [MightyPork/rpw#52]
## RPW 4.2.0 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.

Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com

### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.8.0_45
 Java vendor       | Oracle Corporation
 Java path         | C:\Program Files (x86)\Java\jre1.8.0_45
 OS name           | Windows 8.1
 OS arch           | x86
 File encoding     | Cp1252
 Launch dir        | C:\Users\Taylor\Downloads
 RPW version       | 4.2.0
 Library version   | 1.8.7+1.8
 RPW path          | C:\Users\Taylor\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\Taylor\AppData\Roaming\.minecraft

### STACK TRACE ###

```
java.lang.ClassCastException: javax.swing.plaf.nimbus.DerivedColor$UIResource cannot be cast to javax.swing.Painter
	at javax.swing.plaf.nimbus.NimbusStyle.getBackgroundPainter(Unknown Source)
	at javax.swing.plaf.nimbus.SynthPainterImpl.paintBackground(Unknown Source)
	at javax.swing.plaf.nimbus.SynthPainterImpl.paintPanelBackground(Unknown Source)
	at javax.swing.plaf.synth.SynthPanelUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1300(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

### FULL LOG ###

```
[ i ] Main logger initialized.
[ i ] 2015/06/26 01:28:19
[ i ] ResourcePack Workbench v.4.2.0 (#420)
[ # ] Init started...
[ - ] Checking Minecraft installation.
[ - ] Checking working directory.
[ - ] Initializing configuration manager.
[   ] Last run version: 4.1.0 (#410)
[ i ] Using library version: 1.8.7+1.8
[ - ] Loading GUI icons
[ - ] Loading GUI icons - done.
[   ] Initializing RSyntaxTextArea
[ - ] Loading help pages
[ # ] Initializing Sources
[ - ] Loading vanilla structure
[ - ] Loading help pages - done.
[ - ] Loading vanilla structure - done.
[ - ] Erasing library cache
[ - ] Loading resourcepacks...
[ # ] Initializing Sources - done.
[ - ] Building main window.
[ - ] Downloading update info
[ - ] Opening last project (if any).
[ # ] Loading project 4th of July
[ - ] Project '4th of July': Creating backup copy...
[ - ] Project '4th of July': Copying - done.
[ - ] Project '4th of July':  Loading from workdir
[   ] Adding RPW_README.txt to the pack
[   ] Retrieving changelog fragment 411
[!E!] Null stream to be converted to String, using empty instead.
[   ] Retrieving changelog fragment 412
[!E!] Null stream to be converted to String, using empty instead.
[   ] Retrieving changelog fragment 413
[!E!] Null stream to be converted to String, using empty instead.
[   ] Retrieving changelog fragment 414
[!E!] Null stream to be converted to String, using empty instead.
[   ] Retrieving changelog fragment 415
[!E!] Null stream to be converted to String, using empty instead.
[   ] Retrieving changelog fragment 416
[!E!] Null stream to be converted to String, using empty instead.
[   ] Retrieving changelog fragment 417
[!E!] Null stream to be converted to String, using empty instead.
[   ] Retrieving changelog fragment 418
[!E!] Null stream to be converted to String, using empty instead.
[   ] Retrieving changelog fragment 419
[!E!] Null stream to be converted to String, using empty instead.
[   ] Retrieving changelog fragment 420
[ - ] Downloading update info - done.
[ i ] Your version is up-to-date.
[   ] Dialog closed: What's new
[   ] Dialog open: What's new
[   ] Dialog closed: Sound Wizard
[   ] Dialog open: Sound Wizard
[   ] Dialog closed: Sound Wizard
[   ] Dialog open: Sound Wizard
[   ] Dialog closed: Export
[   ] Dialog open: Export
[   ] Dialog open: Exporting project
[ # ] Exporting project "4th of July" to C:\Users\Taylor\AppData\Roaming\.minecraft\resourcepacks\4th of July.zip
[ - ] Preparing zip builder.
[ - ] Exporting included extra files.
[ - ] Exporting custom sounds.
[   ] + assets/minecraft/sounds/hero.ogg
[ - ] Exporting custom languages.
[ - ] Exporting configuration files.
[   ] + pack.png
[   ] + readme.txt
[   ] + assets/minecraft/sounds.json
[   ] + pack.mcmeta
[ - ] Exporting project assets.
[ - ] Adding project asset files.
[   ] Writing to MC options: resourcePacks:["4th of July.zip"]
[ i ] Minecraft config file was changed.
[ # ] Exporting project "4th of July" to C:\Users\Taylor\AppData\Roaming\.minecraft\resourcepacks\4th of July.zip - done.
[ i ] Export successful.
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.ClassCastException: javax.swing.plaf.nimbus.DerivedColor$UIResource cannot be cast to javax.swing.Painter
[!E!] 	at javax.swing.plaf.nimbus.NimbusStyle.getBackgroundPainter(Unknown Source)
[!E!] 	at javax.swing.plaf.nimbus.SynthPainterImpl.paintBackground(Unknown Source)
[!E!] 	at javax.swing.plaf.nimbus.SynthPainterImpl.paintPanelBackground(Unknown Source)
[!E!] 	at javax.swing.plaf.synth.SynthPanelUI.update(Unknown Source)
[!E!] 	at javax.swing.JComponent.paintComponent(Unknown Source)
[!E!] 	at javax.swing.JComponent.paint(Unknown Source)
[!E!] 	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
[!E!] 	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
[!E!] 	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
[!E!] 	at javax.swing.RepaintManager.paint(Unknown Source)
[!E!] 	at javax.swing.JComponent._paintImmediately(Unknown Source)
[!E!] 	at javax.swing.JComponent.paintImmediately(Unknown Source)
[!E!] 	at javax.swing.RepaintManager$4.run(Unknown Source)
[!E!] 	at javax.swing.RepaintManager$4.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[!E!] 	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
[!E!] 	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
[!E!] 	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
[!E!] 	at javax.swing.RepaintManager.access$1300(Unknown Source)
[!E!] 	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
[!E!] 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.EventQueue.access$500(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.run(Unknown Source)
[!E!] 

```

~~~ END OF REPORT ~~~

**Comment by MightyPork** [comment]
Hi, this is a bug in the Java UI library, it happens sometimes on Windows.
To fix, disable the Nimbus theme:

- if you can open RPW, go to Settings menu, and uncheck Nimbus
- if you can't open RPW, find the config file and change it to false (just search the file for "nimbus" and you'll find it). RPW's folder is ~/.mcRPW (next to .minecraft)
