### ISSUE TITLE
Crash when using export/import 

### ISSUE THREAD

**Issue by CreateYourPersonalAcc** [MightyPork/rpw#64]
This is the log it gets to 80 precent then crashes.

## RPW 4.3.0 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.

Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com

### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.8.0_45
 Java vendor       | Oracle Corporation
 Java path         | C:\Program Files\Java\jre1.8.0_45
 OS name           | Windows 8.1
 OS arch           | amd64
 File encoding     | Cp1252
 Launch dir        | C:\Users\Jonah\Desktop\Minecraft Texture Pack Creators
 RPW version       | 4.3.0
 Library version   | 1.8.8+1.8
 RPW path          | C:\Users\Jonah\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\Jonah\AppData\Roaming\.minecraft

### STACK TRACE ###

```
java.lang.NullPointerException
	at net.mightypork.rpw.tasks.sequences.SequenceExportProject.stepAddConfigFiles(SequenceExportProject.java:170)
	at net.mightypork.rpw.tasks.sequences.SequenceExportProject.step(SequenceExportProject.java:93)
	at net.mightypork.rpw.tasks.sequences.AbstractSequence.run(AbstractSequence.java:106)
	at net.mightypork.rpw.tasks.sequences.AbstractSequence.run(AbstractSequence.java:75)
	at net.mightypork.rpw.tasks.Tasks$6.run(Tasks.java:386)
	at java.lang.Thread.run(Unknown Source)

```

### FULL LOG ###

```
[ i ] Main logger initialized.
[ i ] 2015/10/10 22:49:41
[ i ] ResourcePack Workbench v.4.3.0 (#430)
[ # ] Init started...
[ - ] Checking Minecraft installation.
[ - ] Checking working directory.
[ - ] Initializing configuration manager.
[   ] Last run version: 4.3.0 (#430)
[ i ] Using library version: 1.8.8+1.8
[ - ] Loading GUI icons
[ - ] Loading GUI icons - done.
[   ] Initializing RSyntaxTextArea
[ - ] Loading help pages
[ # ] Initializing Sources
[ - ] Loading vanilla structure
[ - ] Loading help pages - done.
[ - ] Loading vanilla structure - done.
[ - ] Erasing library cache
[ - ] Loading resourcepacks...
[ # ] Initializing Sources - done.
[ - ] Building main window.
[ - ] Downloading update info
[ - ] Opening last project (if any).
[ # ] Loading project Ze Ultimate Texture Pack 2.0
[ - ] Project 'Ze Ultimate Texture Pack 2.0': Creating backup copy...
[ - ] Project 'Ze Ultimate Texture Pack 2.0': Copying - done.
[ - ] Project 'Ze Ultimate Texture Pack 2.0':  Loading from workdir
[   ] Adding RPW_README.txt to the pack
[!E!] NPE from issue #45 happened again
[!E!] java.lang.NullPointerException
[!E!] 	at net.mightypork.rpw.project.Project.saveConfigFiles(Project.java:230)
[!E!] 	at net.mightypork.rpw.project.Project.reload(Project.java:134)
[!E!] 	at net.mightypork.rpw.project.Project.init(Project.java:76)
[!E!] 	at net.mightypork.rpw.project.Project.<init>(Project.java:65)
[!E!] 	at net.mightypork.rpw.project.Projects.openProject(Projects.java:86)
[!E!] 	at net.mightypork.rpw.tasks.Tasks$16$1.run(Tasks.java:792)
[!E!] 	at java.lang.Thread.run(Unknown Source)
[!E!] 
[ - ] Downloading update info - done.
[ i ] Your version is up-to-date.
[   ] Dialog closed: Export
[   ] Dialog open: Export
[!E!] NPE from issue #45 happened again
[!E!] java.lang.NullPointerException
[!E!] 	at net.mightypork.rpw.project.Project.saveConfigFiles(Project.java:230)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskStoreProjectChanges(Tasks.java:289)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskStoreProjectChanges(Tasks.java:273)
[!E!] 	at net.mightypork.rpw.tasks.Tasks$6.run(Tasks.java:384)
[!E!] 	at java.lang.Thread.run(Unknown Source)
[!E!] 
[   ] Dialog open: Exporting project
[ # ] Exporting project "Ze Ultimate Texture Pack 2.0" to C:\Users\Jonah\AppData\Roaming\.minecraft\resourcepacks\Ze Ultimate Texture Pack 2.0.zip
[ - ] Preparing zip builder.
[ - ] Exporting included extra files.
[ - ] Exporting custom sounds.
[ - ] Exporting custom languages.
[ - ] Exporting configuration files.
[   ] + pack.png
[   ] + readme.txt
[   ] + assets/minecraft/sounds.json
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.NullPointerException
[!E!] 	at net.mightypork.rpw.tasks.sequences.SequenceExportProject.stepAddConfigFiles(SequenceExportProject.java:170)
[!E!] 	at net.mightypork.rpw.tasks.sequences.SequenceExportProject.step(SequenceExportProject.java:93)
[!E!] 	at net.mightypork.rpw.tasks.sequences.AbstractSequence.run(AbstractSequence.java:106)
[!E!] 	at net.mightypork.rpw.tasks.sequences.AbstractSequence.run(AbstractSequence.java:75)
[!E!] 	at net.mightypork.rpw.tasks.Tasks$6.run(Tasks.java:386)
[!E!] 	at java.lang.Thread.run(Unknown Source)
[!E!] 

```

~~~ END OF REPORT ~~~

**Comment by MightyPork** [comment]
Not exactly sure what is the problem but for now try to change your pack name to something normal (no spaces and weird stuff). The Title is what is shown in MC (close project and use the manage projects wizard to rename, I think)

**Comment by lolerlion** [comment]
how do I open a different editor I always get cant find blah blah blah now luaching system editor

**Comment by MightyPork** [comment]
can't you people read the help or something. there's a config dialog in the settings

**Comment by MightyPork** [comment]
No idea if it fixes it, but next version makes sure new projects don't have bad characters in file names. Closing as I can't repro this anyway
