### ISSUE TITLE
Rpw CRASH! help

### ISSUE THREAD

**Issue by cookierexx** [MightyPork/rpw#65]
## RPW 4.3.0 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.

Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com

### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.7.0_80
 Java vendor       | Oracle Corporation
 Java path         | C:\Program Files\Java\jre7
 OS name           | Windows 7
 OS arch           | amd64
 File encoding     | Cp1252
 Launch dir        | C:\Users\px\AppData\Roaming\.mcRPW
 RPW version       | 4.3.0
 Library version   | null
 RPW path          | C:\Users\px\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\px\AppData\Roaming\.minecraft

### STACK TRACE ###

```
java.lang.NoClassDefFoundError: java/awt/image/DataBuffer$1
	at java.awt.image.DataBuffer.<clinit>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at sun.awt.image.ImageRepresentation.createBufferedImage(Unknown Source)
	at sun.awt.image.ImageRepresentation.setPixels(Unknown Source)
	at sun.awt.image.ImageDecoder.setPixels(Unknown Source)
	at sun.awt.image.PNGImageDecoder.sendPixels(Unknown Source)
	at sun.awt.image.PNGImageDecoder.produceImage(Unknown Source)
	at sun.awt.image.InputStreamImageSource.doFetch(Unknown Source)
	at sun.awt.image.ImageFetcher.fetchloop(Unknown Source)
	at sun.awt.image.ImageFetcher.run(Unknown Source)

**Comment by MightyPork** [comment]
That's a new one. Something's wrong with your Java.
I'd recommend re-installing Java, and preferably update to Java 8, while you're at it.

**Comment by cookierexx** [comment]
ok!!! nice it works someting was wrong with my java ...maybe java force me to update my java lol XD  thanks a lot !!!
