### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by CrazyCanine** [MightyPork/rpw#71]

**Comment by CrazyCanine** [comment]
## RPW 4.3.0 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.


Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com


### SYSTEM INFO ###


 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.8.0_65
 Java vendor       | Oracle Corporation
 Java path         | C:\Program Files\Java\jre1.8.0_65
 OS name           | Windows 10
 OS arch           | amd64
 File encoding     | Cp1252
 Launch dir        | C:\WINDOWS\system32
 RPW version       | 4.3.0
 Library version   | 1.8.8-OptiFine_HD_U_F3+1.8
 RPW path          | C:\Users\HP\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\HP\AppData\Roaming\.minecraft


### STACK TRACE ###


```
java.lang.NullPointerException
	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:217)
	at net.mightypork.rpw.utils.files.FileUtils.delete(FileUtils.java:197)
	at net.mightypork.rpw.utils.files.FileUtils.delete(FileUtils.java:179)
	at net.mightypork.rpw.project.Project.createBackup(Project.java:288)
	at net.mightypork.rpw.project.Project.init(Project.java:74)
	at net.mightypork.rpw.project.Project.<init>(Project.java:65)
	at net.mightypork.rpw.project.Projects.openProject(Projects.java:86)
	at net.mightypork.rpw.project.Projects.openNewProject(Projects.java:95)
	at net.mightypork.rpw.gui.windows.dialogs.DialogNewProject$5$1.run(DialogNewProject.java:293)
	at net.mightypork.rpw.tasks.Tasks.taskAskToSaveIfChanged(Tasks.java:463)
	at net.mightypork.rpw.gui.windows.dialogs.DialogNewProject$5.actionPerformed(DialogNewProject.java:284)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at net.mightypork.rpw.gui.windows.RpwDialog.setVisible(RpwDialog.java:202)
	at net.mightypork.rpw.gui.windows.RpwDialog.openDialog(RpwDialog.java:143)
	at net.mightypork.rpw.gui.Gui.open(Gui.java:147)
	at net.mightypork.rpw.tasks.Tasks.taskDialogNewProject(Tasks.java:874)
	at net.mightypork.rpw.tasks.Tasks.taskNewProject(Tasks.java:763)
	at net.mightypork.rpw.gui.widgets.MenuMain$1.actionPerformed(MenuMain.java:482)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```


### FULL LOG ###


```
[ i ] Main logger initialized.
[ i ] 2016/02/17 14:59:49
[ i ] ResourcePack Workbench v.4.3.0 (#430)
[ # ] Init started...
[ - ] Checking Minecraft installation.
[ - ] Checking working directory.
[ - ] Initializing configuration manager.
[   ] Last run version: 4.3.0 (#430)
[ i ] Using library version: 1.8.8-OptiFine_HD_U_F3+1.8
[ - ] Loading GUI icons
[ - ] Loading GUI icons - done.
[   ] Initializing RSyntaxTextArea
[ # ] Initializing Sources
[ - ] Loading help pages
[ - ] Loading vanilla structure
[ - ] Loading help pages - done.
[ - ] Loading vanilla structure - done.
[ - ] Erasing library cache
[ - ] Loading resourcepacks...
[ # ] Initializing Sources - done.
[ - ] Building main window.
[ - ] Downloading update info
[ - ] Opening last project (if any).
[ # ] Loading project Random
[ - ] Project 'Random': Creating backup copy...
[ - ] Project 'Random': Copying - done.
[ - ] Project 'Random':  Loading from workdir
[   ] Adding RPW_README.txt to the pack
[ - ] Downloading update info - done.
[ i ] Your version is up-to-date.
[ - ] Checking project for unsaved changes.
[   ] Project 'Random': Finding differences BACKUP:WORKDIR
[   ] Checksums calculated in 31 ms
[   ] Project 'Random': No changes found.
[   ] Dialog closed: New Project
[ - ] Project 'Painting addon': Creating backup copy...
[ - ] Project 'Painting addon': Copying - done.
[ - ] Project 'Painting addon':  Loading from workdir
[   ] Adding default pack icon
[   ] Adding RPW_README.txt to the pack
[   ] Dialog open: New Project
[ - ] Checking project for unsaved changes.
[   ] Project 'Painting addon': Finding differences BACKUP:WORKDIR
[   ] Checksum mismatch:
[   ] Child counts differ:
[   ] C:\Users\HP\AppData\Roaming\.mcRPW\tmp\backup-Painting addon
[   ] C:\Users\HP\AppData\Roaming\.mcRPW\projects\Painting addon
[   ] Project 'Painting addon': Changes detected
[   ] Asking to save.
[   ] - User choice DISCARD
[ - ] Reverting project changes, restoring from backup.
[   ] Dialog closed: New Project
[ - ] Project 'Painting addon': Restoring project files from backup.
[ - ] Project 'Painting addon': Restoring - done.
[ - ] Project 'Painting addon':  Loading from workdir
[   ] Adding default pack icon
[   ] Adding RPW_README.txt to the pack
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.NullPointerException
[!E!] 	at net.mightypork.rpw.utils.files.FileUtils.delete_do(FileUtils.java:217)
[!E!] 	at net.mightypork.rpw.utils.files.FileUtils.delete(FileUtils.java:197)
[!E!] 	at net.mightypork.rpw.utils.files.FileUtils.delete(FileUtils.java:179)
[!E!] 	at net.mightypork.rpw.project.Project.createBackup(Project.java:288)
[!E!] 	at net.mightypork.rpw.project.Project.init(Project.java:74)
[!E!] 	at net.mightypork.rpw.project.Project.<init>(Project.java:65)
[!E!] 	at net.mightypork.rpw.project.Projects.openProject(Projects.java:86)
[!E!] 	at net.mightypork.rpw.project.Projects.openNewProject(Projects.java:95)
[!E!] 	at net.mightypork.rpw.gui.windows.dialogs.DialogNewProject$5$1.run(DialogNewProject.java:293)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskAskToSaveIfChanged(Tasks.java:463)
[!E!] 	at net.mightypork.rpw.gui.windows.dialogs.DialogNewProject$5.actionPerformed(DialogNewProject.java:284)
[!E!] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[!E!] 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
[!E!] 	at java.awt.Component.processMouseEvent(Unknown Source)
[!E!] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.Component.processEvent(Unknown Source)
[!E!] 	at java.awt.Container.processEvent(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.EventQueue.access$500(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[!E!] 	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
[!E!] 	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
[!E!] 	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.awt.WaitDispatchSupport.enter(Unknown Source)
[!E!] 	at java.awt.Dialog.show(Unknown Source)
[!E!] 	at java.awt.Component.show(Unknown Source)
[!E!] 	at java.awt.Component.setVisible(Unknown Source)
[!E!] 	at java.awt.Window.setVisible(Unknown Source)
[!E!] 	at java.awt.Dialog.setVisible(Unknown Source)
[!E!] 	at net.mightypork.rpw.gui.windows.RpwDialog.setVisible(RpwDialog.java:202)
[!E!] 	at net.mightypork.rpw.gui.windows.RpwDialog.openDialog(RpwDialog.java:143)
[!E!] 	at net.mightypork.rpw.gui.Gui.open(Gui.java:147)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskDialogNewProject(Tasks.java:874)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskNewProject(Tasks.java:763)
[!E!] 	at net.mightypork.rpw.gui.widgets.MenuMain$1.actionPerformed(MenuMain.java:482)
[!E!] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[!E!] 	at javax.swing.AbstractButton.doClick(Unknown Source)
[!E!] 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
[!E!] 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
[!E!] 	at java.awt.Component.processMouseEvent(Unknown Source)
[!E!] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.Component.processEvent(Unknown Source)
[!E!] 	at java.awt.Container.processEvent(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.EventQueue.access$500(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.run(Unknown Source)
[!E!] 

```


~~~ END OF REPORT ~~~

**Comment by MightyPork** [comment]
how did it happen?

**Comment by CrazyCanine** [comment]
i was creating a new pack, i dont know how it happened though

**Comment by MightyPork** [comment]
can you reproduce it?
Also don't use spaces in the project name. Put them in the Title if needed.
I suspect it triggers some weird bug on Windows
