### ISSUE TITLE
Crash report upon opening RPW

### ISSUE THREAD

**Issue by dapper-deoxys** [MightyPork/rpw#83]
## RPW 4.3.1 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.

Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com

### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.6.0_05
 Java vendor       | Sun Microsystems Inc.
 Java path         | C:\Program Files (x86)\Java\jre1.6.0_05
 OS name           | Windows Vista
 OS arch           | x86
 File encoding     | Cp1252
 Launch dir        | C:\Users\duch3\Downloads
 RPW version       | 4.3.1
 Library version   | UNKNOWN
 RPW path          | C:\Users\duch3\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\duch3\AppData\Roaming\.minecraft

### STACK TRACE ###

```
java.lang.UnsupportedClassVersionError: com/github/rjeschke/txtmark/Decorator : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$000(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClassInternal(Unknown Source)
	at net.mightypork.rpw.App.init(App.java:108)
	at net.mightypork.rpw.App.start(App.java:61)
	at net.mightypork.rpw.App.main(App.java:55)

```

### FULL LOG ###

```
[ i ] Main logger initialized.
[ i ] 2016/06/03 19:54:59
[ i ] ResourcePack Workbench v.4.3.1 (#431)
[ # ] Init started...
[ - ] Checking Minecraft installation.
[ - ] Checking working directory.
[ - ] Initializing configuration manager.
[   ] Last run version: 4.3.1 (#431)
[ i ] Using library version: UNKNOWN
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.UnsupportedClassVersionError: com/github/rjeschke/txtmark/Decorator : Unsupported major.minor version 51.0
[!E!] 	at java.lang.ClassLoader.defineClass1(Native Method)
[!E!] 	at java.lang.ClassLoader.defineClass(Unknown Source)
[!E!] 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[!E!] 	at java.net.URLClassLoader.defineClass(Unknown Source)
[!E!] 	at java.net.URLClassLoader.access$000(Unknown Source)
[!E!] 	at java.net.URLClassLoader$1.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.net.URLClassLoader.findClass(Unknown Source)
[!E!] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[!E!] 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[!E!] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[!E!] 	at java.lang.ClassLoader.loadClassInternal(Unknown Source)
[!E!] 	at net.mightypork.rpw.App.init(App.java:108)
[!E!] 	at net.mightypork.rpw.App.start(App.java:61)
[!E!] 	at net.mightypork.rpw.App.main(App.java:55)
[!E!] 

```

~~~ END OF REPORT ~~~

**Comment by MightyPork** [comment]
Update your java, RPW needs 1.7.
You are two versions behind.
